services:
  postgres:
    image: postgres:latest
    container_name: delivery_nestjs_postgres
    environment:
      POSTGRES_USER: ilyas
      POSTGRES_PASSWORD: password
      POSTGRES_DB: delivery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ilyas -d delivery_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: delivery_nestjs_backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=ilyas
      - DB_PASSWORD=password
      - DB_NAME=delivery_db
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
